//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ApplicationID { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<double> Date { get; set; }
        public string Status { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public Nullable<double> Prepayment { get; set; }
        public Nullable<double> DeliveryDate { get; set; }
    
        public virtual Partners Partners { get; set; }
    }
}
