//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.AccessTypes = new HashSet<AccessTypes>();
            this.EquipmentTypes = new HashSet<EquipmentTypes>();
        }
    
        public int EmployeesID { get; set; }
        public string EmployeesName { get; set; }
        public Nullable<int> PostID { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ProductsID { get; set; }
        public string Email { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessTypes> AccessTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentTypes> EquipmentTypes { get; set; }
    }
}
