//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int PartnerID { get; set; }
        public string PartnerGroupName { get; set; }
        public Nullable<double> Raiting { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public string Address { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual PartnerTypes PartnerTypes { get; set; }
    }
}
